include: package:lint/analysis_options.yaml

linter:
  rules:
    parameter_assignments: true
    sort_pub_dependencies: false
    # avoid_function_literals_in_foreach_calls: false

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"